buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath 'info.solidsoft.gradle.pitest:gradle-pitest-plugin:1.5.2'
		classpath "org.openapitools:openapi-generator-gradle-plugin:6.6.0"
	}
}

plugins {
	id 'java'

	// Spring
	id 'org.springframework.boot' version '2.7.18'
	id 'io.spring.dependency-management' version '1.0.15.RELEASE'

	// Test coverage
	id 'jacoco'

	// Code style
	id 'checkstyle'

	// PMD
	id 'pmd'

	// PITest
	id 'info.solidsoft.pitest' version '1.15.0'
}

group = 'nl.tudelft.cse.sem.v20232024.team08b'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

// Only the executable boot jar is needed
jar {
	enabled = false
}

repositories {
	mavenCentral()
}

dependencies {
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	// Swagger UI and OpenAPI document generation from controller annotations
	implementation 'org.springdoc:springdoc-openapi-ui:1.7.0'

	// Embedded database
	implementation 'com.h2database:h2'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.junit.jupiter:junit-jupiter'
	testImplementation 'org.mockito:mockito-core'
	testImplementation 'org.assertj:assertj-core'
}

test {
	useJUnitPlatform()
	jacoco {
		enabled = true
		includes = ['nl.tudelft.sem.v20232024.team08b.*']
	}
}

jacoco {
	toolVersion = "0.8.12"
}
jacocoTestReport {
	reports {
		xml.required = true
		html.required = true
	}
	afterEvaluate {
		classDirectories.setFrom(files(classDirectories.files.collect {
			fileTree(dir: it, exclude: ['**/submissions/**',
										'**/users/**',
										'**/ignore/**',
										'**/config/**',
										'**/demo/**'])
		}))
	}
}
jacocoTestCoverageVerification() {
	dependsOn test
	violationRules {
		rule {
			enabled = true
			element = 'CLASS'
			includes = ['nl.tudelft.sem.v20232024.team08b.*']
			excludes = ['nl.tudelft.sem.v20232024.team08b.dtos.submissions',
						'nl.tudelft.sem.v20232024.team08b.dtos.users',
						'ignore']
			limit {
				counter = 'BRANCH'
				value = 'COVEREDRATIO'
				minimum = 0.0
			}
		}
	}
}

checkstyle {
	toolVersion "8.37"
	configFile = file("${rootDir}/config/checkstyle/checkstyle.xml")
	ignoreFailures = false
	maxErrors = 0
	maxWarnings = 0
}
pmd {

	incrementalAnalysis = true
	sourceSets = [sourceSets.main]
	ruleSetFiles = files("${rootDir}/config/pmd/errorprone.xml")    // exactly path as in your lib classpath
	ruleSets = []
}



apply plugin: 'info.solidsoft.pitest'
pitest {
	//adds dependency to org.pitest:pitest-junit5-plugin and sets "testPlugin" to "junit5"
	junit5PluginVersion = '1.2.1'

	targetClasses = ['nl.tudelft.sem.v20232024.team08b.*']  //by default "${project.group}.*"
	excludedClasses = ['nl.tudelft.sem.v20232024.team08b.config.*',
					   'nl.tudelft.sem.v20232024.team08b.demo.*',
					   'nl.tudelft.sem.v20232024.team08b.dtos.*']	// exclude dtos from testing
	pitestVersion = '1.15.2'
	threads = 4
	outputFormats = ['XML', 'HTML']
	timestampedReports = false
}

apply plugin: 'org.openapi.generator'
task generateSubmissions(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
	generatorName.set("spring")
	inputSpec.set("$rootDir/reviews-microservice/src/main/resources/teamA.yaml")
	outputDir.set("$buildDir/generated")
	modelPackage.set("nl.tudelft.sem.v20232024.team08b.dtos.submissions")
	apiPackage.set("ignore")
	configOptions.set([
			interfaceOnly: 'true',
			openApiNullable: 'false'
	])
}
task generateUsers(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
	generatorName.set("spring")
	inputSpec.set("$rootDir/reviews-microservice/src/main/resources/teamC.yaml")
	outputDir.set("$buildDir/generated")
	modelPackage.set("nl.tudelft.sem.v20232024.team08b.dtos.users")
	apiPackage.set("ignore")
	configOptions.set([
			interfaceOnly: 'true',
			openApiNullable: 'false'
	])
}

compileJava.dependsOn tasks.named("generateSubmissions")
compileJava.dependsOn tasks.named("generateUsers")

sourceSets {
	getByName("main") {
		java {
			srcDir("$buildDir/generated/src/main/java")
		}
	}
}
